name: courses_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  cupertino_icons: ^1.0.0
  animate_do: ^4.2.0
  bloc: ^9.1.0
  adaptive_platform_ui: ^0.1.100
  cached_network_image: ^3.4.1
  dropdown_button2: ^2.3.9
  easy_localization: ^3.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^10.0.0
  fluttertoast: ^9.0.0
  gap: ^3.0.1
  get_it: ^9.2.0
  google_fonts: ^6.3.3
  image_picker: ^1.2.1
  shared_preferences: ^2.5.4
  skeletonizer: ^2.1.2
  flutter_lazy_indexed_stack: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ali.jpg
    - assets/images/
    - assets/translations/
    - assets/fonts/
    - assets/icons/
